# 服务端口
server:
  port: 8080
# 配置rabbitmq服务
spring:
  rabbitmq:
   username: 用户名
   password: 密码
   virtual-host: /
   connection-timeout: 16000
   addresses: ip地址1:端口1, ip地址2:端口2,ip地址3:端口3,
  # 启用消息确认模式
   publisher-confirm-type: correlated

  # 启用 return 消息模式
   publisher-returns: true
   template:
    mandatory: true
