# 服务端口
server:
  port: 8080
# 配置rabbitmq服务
spring:
  rabbitmq:
   username: admin1
   password: 123
   virtual-host: /
   connection-timeout: 16000
   addresses: 43.142.85.155:5673, 43.142.85.155:5674,43.142.85.155:5675,
  # 启用消息确认模式
   publisher-confirm-type: correlated

  # 启用 return 消息模式
   publisher-returns: true
   template:
    mandatory: true